% -------------------------------------------------------------------
%  Generated by MATLAB on 8-Sep-2021 22:27:27
%  MATLAB version: 9.4.0.857798 (R2018a) Update 2
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

mld = saveVarsMat.mld; % <700x567x3 uint8> too many elements

mld_brig = saveVarsMat.mld_brig; % <700x567 uint8> too many elements

mld_bw = saveVarsMat.mld_bw; % <700x567 logical> too many elements

mld_gray = saveVarsMat.mld_gray; % <700x567 uint8> too many elements

mld_gray_const = saveVarsMat.mld_gray_const; % <700x567 uint8> too many elements

mld_kontras = saveVarsMat.mld_kontras; % <700x567x3 uint8> too many elements

clear saveVarsMat;
